# Schemas declaration
hwpc_columns = [
    ("timestamp", int),
    ("sensor", str),
    ("target", str),
    ("socket", int),
    ("cpu", int),
    ("rapl_energy_pkg", int),
    ("rapl_energy_dram", int),
    ("rapl_energy_cores", int),
    ("time_enabled", int),
    ("time_running", int),
    ("nb_core", int),
    ("nb_ops_per_core", int),
    ("iteration", int),
    ("alone", bool),
    ("site", str),
    ("clstr", str),
    ("node", str),
]

perf_columns = [
    ("power_energy_pkg", float),
    ("power_energy_ram", float),
    ("power_energy_cores", float),
    ("time_elapsed", float),
    ("nb_core", int),
    ("nb_ops_per_core", int),
    ("iteration", int),
    ("alone", bool),
    ("site", str),
    ("clstr", str),
    ("node", str),
]

energy_columns = [
    ("node", str),
    ("task", str),
    ("nb_core", int),
    ("nb_ops_per_core", int),
    ("iteration", int),
    ("alone", bool),
    ("energy_pkg", float),
    ("energy_cores", float),
    ("energy_ram", float),
]

stats_columns = [
    ("node", str),
    ("task", str),
    ("nb_core", int),
    ("nb_ops_per_core", int),
    ("alone", bool),
    ("pkg_minimum", float),
    ("pkg_maximum", float),
    ("pkg_average", float),
    ("pkg_median", float),
    ("pkg_standard_deviation", float),
    ("pkg_quantile_25", float),
    ("pkg_quantile_75", float),
    ("pkg_coefficient_of_variation", float),
    ("cores_minimum", float),
    ("cores_maximum", float),
    ("cores_average", float),
    ("cores_median", float),
    ("cores_standard_deviation", float),
    ("cores_quantile_25", float),
    ("cores_quantile_75", float),
    ("cores_coefficient_of_variation", float),
    ("ram_minimum", float),
    ("ram_maximum", float),
    ("ram_average", float),
    ("ram_median", float),
    ("ram_standard_deviation", float),
    ("ram_quantile_25", float),
    ("ram_quantile_75", float),
    ("ram_coefficient_of_variation", float),
]

nodes_configuration_columns = [
    ("uid", str),
    ("clstr", str),
    ("exotic", bool),
    ("architecture_nb_cores", int),
    ("architecture_nb_threads", int),
    ("processor_vendor", str),
    ("processor_clock_speed", int),
    ("processor_instruction_set", str),
    ("processor_ht_capable", bool),
    ("processor_microarchitecture", str),
    ("processor_microcode", str),
    ("processor_model", str),
    ("processor_version", str),
    ("os_cstate_driver", str),
    ("os_cstate_governor", str),
    ("os_pstate_driver", str),
    ("os_pstate_governor", str),
    ("os_turboboost_enabled", bool),
]
